version: "3.9"

networks:
  common-net:
    external: false

services:
  mysql:
    image: mysql:8.0.25
    privileged: true
    container_name: mysql
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - common-net
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysqlconfig/cnf:/etc/mysql/conf.d
      - ./mysqlconfig/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

  nginx:
    image: nginx:1.21.0-alpine
    privileged: true
    container_name: nginx
    networks:
      - common-net
    volumes:
      - /path/to/local/workspace:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NGINX_PORT=80
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  
  php:
    image: shuixiang/phpdev:8.0.7-swoole4.6.7-alpine3.13
    privileged: true
    container_name: php
    networks:
      - common-net
    volumes:
      - /path/to/local/workspace:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    restart: always
    # ports:
    #   - "127.0.0.1:9000:9000"

  php74:
    image: shuixiang/phpdev:7.4.23-swoole4.6.7-alpine3.14
    privileged: true
    container_name: php74
    networks:
      - common-net
    volumes:
      - /path/to/local/workspace:/var/www/html
      - ./php/php.ini:/usr/local/etc/php74/php.ini
    restart: always
    # ports:
    #   - "127.0.0.1:9001:9000"
  
  redis:
    image: redis:6.2.4-alpine3.13
    privileged: true
    container_name: redis-server
    networks:
      - common-net
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    ports:
      - "6379:6379"